on:
    push:
        branches:
            - main
            - epic/Project-Service
        tags:
            - 'v*'

env:
    REGISTRY: ghcr.io

jobs:
    project-service:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - 
                name: Checkout
                uses: actions/checkout@v4
            
            - 
                name: Log in to the Container registry
                uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            - 
                name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ env.REGISTRY }}/${{ github.repository }}-ProjectService
                    tags: |
                        type=schedule
                        type=semver,pattern={{version}}
                        type=semver,pattern={{version}},prefix=v
                        type=semver,pattern={{major}}.{{minor}}
                        type=semver,pattern={{major}}.{{minor}},prefix=v
                        type=semver,pattern={{major}}
                        type=semver,pattern={{major}},prefix=v
                        type=ref,event=branch
                        type=ref,event=pr
                        type=sha
                        type=raw,value=latest

            - 
                name: Build
                uses: docker/build-push-action@v2
                with:
                    context: ./ProjectService
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
