name: Node.js CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-auth-service:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 19.x ]
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ./auth-service
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
        working-directory: ./auth-service
      - name: Run tests and check coverage
        run: npm run cover:check
        working-directory: ./auth-service
